# Generated by Django 4.0.4 on 2022-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('day_temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('night_temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humidity', models.IntegerField()),
            ],
        ),
    ]
