default: 
  SECRET_KEY: ""
  DEBUG: true
  ALLOWED_HOSTS: ["127.0.0.1",
                  "localhost"]
  DATABASE_URL: ""
  API_KEY: ""

docker:
  DEBUG: false
  DJANGO_SUPERUSER_PASSWORD: 12345678
  DJANGO_SUPERUSER_EMAIL: hacharoky86@gmail.com
  DJANGO_SUPERUSER_USERNAME: admin
 